"to copy, free of charge and under the terms of this License, through a" // new_line('a') // &
"publicly available network server or other readily accessible means," // new_line('a') // &
"then you must either (1) cause the Corresponding Source to be so" // new_line('a') // &
"available, or (2) arrange to deprive yourself of the benefit of the" // new_line('a') // &
"patent license for this particular work, or (3) arrange, in a manner" // new_line('a') // &
"consistent with the requirements of this License, to extend the patent" // new_line('a') // &
"license to downstream recipients.  ""Knowingly relying"" means you have" // new_line('a') // &
"actual knowledge that, but for the patent license, your conveying the" // new_line('a') // &
"covered work in a country, or your recipient's use of the covered work" // new_line('a') // &
"in a country, would infringe one or more identifiable patents in that" // new_line('a') // &
"country that you have reason to believe are valid." // new_line('a') // &
"" // new_line('a') // &
"  If, pursuant to or in connection with a single transaction or" // new_line('a') // &
"arrangement, you convey, or propagate by procuring conveyance of, a" // new_line('a') // &
"covered work, and grant a patent license to some of the parties" // new_line('a') // &
"receiving the covered work authorizing them to use, propagate, modify" // new_line('a') // &
"or convey a specific copy of the covered work, then the patent license" // new_line('a') // &
"you grant is automatically extended to all recipients of the covered" // new_line('a') // &
"work and works based on it." // new_line('a') // &
"" // new_line('a') // &
"  A patent license is ""discriminatory"" if it does not include within" // new_line('a') // &
"the scope of its coverage, prohibits the exercise of, or is" // new_line('a') // &
"conditioned on the non-exercise of one or more of the rights that are" // new_line('a') // &
"specifically granted under this License.  You may not convey a covered" // new_line('a') // &
"work if you are a party to an arrangement with a third party that is" // new_line('a') // &
"in the business of distributing software, under which you make payment" // new_line('a') // &
"to the third party based on the extent of your activity of conveying" // new_line('a') // &
"the work, and under which the third party grants, to any of the" // new_line('a') // &
"parties who would receive the covered work from you, a discriminatory" // new_line('a') // &
"patent license (a) in connection with copies of the covered work" // new_line('a') // &
"conveyed by you (or copies made from those copies), or (b) primarily" // new_line('a') // &
"for and in connection with specific products or compilations that" // new_line('a') // &
"contain the covered work, unless you entered into that arrangement," // new_line('a') // &
"or that patent license was granted, prior to 28 March 2007." // new_line('a') // &
"" // new_line('a') // &
"  Nothing in this License shall be construed as excluding or limiting" // new_line('a') // &
"any implied license or other defenses to infringement that may" // new_line('a') // &
"otherwise be available to you under applicable patent law." // new_line('a') // &
"" // new_line('a') // &
"  12. No Surrender of Others' Freedom." // new_line('a') // &
"" // new_line('a') // &
"  If conditions are imposed on you (whether by court order, agreement or" // new_line('a') // &
"otherwise) that contradict the conditions of this License, they do not" // new_line('a') // &
"excuse you from the conditions of this License.  If you cannot convey a" // new_line('a') // &
"covered work so as to satisfy simultaneously your obligations under this" // new_line('a') // &
"License and any other pertinent obligations, then as a consequence you may" // new_line('a') // &
"not convey it at all.  For example, if you agree to terms that obligate you" // new_line('a') // &
"to collect a royalty for further conveying from those to whom you convey" // new_line('a') // &
"the Program, the only way you could satisfy both those terms and this" // new_line('a') // &
"License would be to refrain entirely from conveying the Program." // new_line('a') // &
"" // new_line('a') // &
"  13. Use with the GNU Affero General Public License." // new_line('a') // &
"" // new_line('a') // &
"  Notwithstanding any other provision of this License, you have" // new_line('a') // &
"permission to link or combine any covered work with a work licensed" // new_line('a') // &
"under version 3 of the GNU Affero General Public License into a single" // new_line('a') // &
"combined work, and to convey the resulting work.  The terms of this" // new_line('a') // &
"License will continue to apply to the part which is the covered work," // new_line('a') // &
"but the special requirements of the GNU Affero General Public License," // new_line('a') // &
"section 13, concerning interaction through a network will apply to the" // new_line('a') // &
"combination as such." // new_line('a') // &
"" // new_line('a') // &
"  14. Revised Versions of this License." // new_line('a') // &
"" // new_line('a') // &
"  The Free Software Foundation may publish revised and/or new versions of" // new_line('a') // &
"the GNU General Public License from time to time.  Such new versions will" // new_line('a') // &
"be similar in spirit to the present version, but may differ in detail to" // new_line('a') // &
"address new problems or concerns." // new_line('a') // &
"" // new_line('a') // &
"  Each version is given a distinguishing version number.  If the" // new_line('a') // &
"Program specifies that a certain numbered version of the GNU General" // new_line('a') // &
"Public License ""or any later version"" applies to it, you have the" // new_line('a') // &
"option of following the terms and conditions either of that numbered" // new_line('a') // &
"version or of any later version published by the Free Software" // new_line('a') // &
"Foundation.  If the Program does not specify a version number of the" // new_line('a') // &
"GNU General Public License, you may choose any version ever published" // new_line('a') // &
"by the Free Software Foundation." // new_line('a') // &
"" // new_line('a') // &
"  If the Program specifies that a proxy can decide which future" // new_line('a') // &
"versions of the GNU General Public License can be used, that proxy's" // new_line('a') // &
"public statement of acceptance of a version permanently authorizes you" // new_line('a') // &
"to choose that version for the Program." // new_line('a') // &
"" // new_line('a') // &
"  Later license versions may give you additional or different" // new_line('a') // &
"permissions.  However, no additional obligations are imposed on any" // new_line('a') // &
"author or copyright holder as a result of your choosing to follow a" // new_line('a') // &
"later version." // new_line('a') // &
"" // new_line('a') // &
"  15. Disclaimer of Warranty." // new_line('a') // &
"" // new_line('a') // &
"  THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY" // new_line('a') // &
"APPLICABLE LAW.  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT" // new_line('a') // &
"HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM ""AS IS"" WITHOUT WARRANTY" // new_line('a') // &
"OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO," // new_line('a') // &
"THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR" // new_line('a') // &
"PURPOSE.  THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM" // new_line('a') // &
"IS WITH YOU.  SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME THE COST OF" // new_line('a') // &
"ALL NECESSARY SERVICING, REPAIR OR CORRECTION." // new_line('a') // &
"" // new_line('a') // &
"  16. Limitation of Liability." // new_line('a') // &
"" // new_line('a') // &
"  IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING" // new_line('a') // &
"WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS" // new_line('a') // &
"THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY" // new_line('a') // &
"GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE" // new_line('a') // &
"USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF" // new_line('a') // &
"DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD" // new_line('a') // &
"PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS)," // new_line('a') // &
"EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF" // new_line('a') // &
"SUCH DAMAGES." // new_line('a') // &
"" // new_line('a') // &
"  17. Interpretation of Sections 15 and 16." // new_line('a') // &
"" // new_line('a') // &
"  If the disclaimer of warranty and limitation of liability provided" // new_line('a') // &
"above cannot be given local legal effect according to their terms," // new_line('a') // &
"reviewing courts shall apply local law that most closely approximates" // new_line('a') // &
"an absolute waiver of all civil liability in connection with the" // new_line('a') // &
"Program, unless a warranty or assumption of liability accompanies a" // new_line('a') // &
"copy of the Program in return for a fee." // new_line('a') // &
"" // new_line('a') // &
"                     END OF TERMS AND CONDITIONS" // new_line('a') // &
"" // new_line('a') // &
"            How to Apply These Terms to Your New Programs" // new_line('a') // &
"" // new_line('a') // &
"  If you develop a new program, and you want it to be of the greatest" // new_line('a') // &
"possible use to the public, the best way to achieve this is to make it" // new_line('a') // &
"free software which everyone can redistribute and change under these terms." // new_line('a') // &
"" // new_line('a') // &
"  To do so, attach the following notices to the program.  It is safest" // new_line('a') // &
"to attach them to the start of each source file to most effectively" // new_line('a') // &
"state the exclusion of warranty; and each file should have at least" // new_line('a') // &
"the ""copyright"" line and a pointer to where the full notice is found." // new_line('a') // &
"" // new_line('a') // &
"    <one line to give the program's name and a brief idea of what it does.>" // new_line('a') // &
"    Copyright (C) <year>  <name of author>" // new_line('a') // &
"" // new_line('a') // &
"    This program is free software: you can redistribute it and/or modify" // new_line('a') // &
"    it under the terms of the GNU General Public License as published by" // new_line('a') // &
"    the Free Software Foundation, either version 3 of the License, or" // new_line('a') // &
"    (at your option) any later version." // new_line('a') // &
"" // new_line('a') // &
"    This program is distributed in the hope that it will be useful," // new_line('a') // &
"    but WITHOUT ANY WARRANTY; without even the implied warranty of" // new_line('a') // &
"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the" // new_line('a') // &
"    GNU General Public License for more details." // new_line('a') // &
"" // new_line('a') // &
"    You should have received a copy of the GNU General Public License" // new_line('a') // &
"    along with this program.  If not, see <http://www.gnu.org/licenses/>." // new_line('a') // &
"" // new_line('a') // &
"Also add information on how to contact you by electronic and paper mail." // new_line('a') // &
"" // new_line('a') // &
"  If the program does terminal interaction, make it output a short" // new_line('a') // &
"notice like this when it starts in an interactive mode:" // new_line('a') // &
"" // new_line('a') // &
"    <program>  Copyright (C) <year>  <name of author>" // new_line('a') // &
"    This program comes with ABSOLUTELY NO WARRANTY; for details type `show w'." // new_line('a') // &
"    This is free software, and you are welcome to redistribute it" // new_line('a') // &
"    under certain conditions; type `show c' for details." // new_line('a') // &
"" // new_line('a') // &
"The hypothetical commands `show w' and `show c' should show the appropriate" // new_line('a') // &
"parts of the General Public License.  Of course, your program'./tortures commands" // new_line('a') // &
"might be different; for a GUI interface, you would use an ""about box""." // new_line('a') // &
"" // new_line('a') // &
"  You should also get your employer (if you work as a programmer) or school," // new_line('a') // &
"if any, to sign a ""copyright disclaimer"" for the program, if necessary." // new_line('a') // &
"For more information on this, and how to apply and follow the GNU GPL, see" // new_line('a') // &
"<http://www.gnu.org/licenses/>." // new_line('a') // &
"" // new_line('a') // &
"  The GNU General Public License does not permit incorporating your program" // new_line('a') // &
"into proprietary programs.  If your program is a subroutine library, you" // new_line('a') // &
"may consider it more useful to permit linking proprietary applications with" // new_line('a') // &
"the library.  If this is what you want to do, use the GNU Lesser General" // new_line('a') // &
"Public License instead of this License.  But first, please read" // new_line('a') // &
"<http://www.gnu.org/philosophy/why-not-lgpl.html>." // new_line('a')
